### ISSUE TITLE
Problem in XML file: BEAST v2.4.8 Structured birth-death model

### ISSUE THREAD

**Issue by alka26** [Taming-the-BEAST/Structured-birth-death-model#2]
Dear Sir,

taking clue from your advise, I switched to BEAST v2.4.8. I was able to load alignment file and generated XML file and followed the manual for same BEASTv2.4.7. However, while running xml file in BEAST, I am getting following error message:

---------------------------------------------------------
Error 110 parsing the xml input file

validate and intialize error: Error: frequencies must add up to 1 but currently add to 1.0000000000000004.

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='prior' spec='util.CompoundDistribution'>
                  <distribution id='birthDeathMigration.t:Alignment' spec='beast.evolution.speciation.BirthDeathMigrationModel'>

java.lang.RuntimeException: Error: frequencies must add up to 1 but currently add to 1.0000000000000004.
	at beast.evolution.speciation.PiecewiseBirthDeathMigrationDistribution.initAndValidate(Unknown Source)
	at beast.evolution.speciation.BirthDeathMigrationModel.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
-------------------------------------------------------------------------------------
Need your help
Regards

**Comment by jugne** [comment]
Archiving as old and can't reproduce. Please reopen if the issue persists.
