### ISSUE TITLE
bdmm model

### ISSUE THREAD

**Issue by alka26** [Taming-the-BEAST/Structured-birth-death-model#3]
Hi...

When i am running xml file for doing bdmm model in Beast 2.4.7, i am getting following error message:

"Error 110 parsing the xml input file

validate and intialize error: Error: frequencies must add up to 1 but currently add to 1.0000000000000004.

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='prior' spec='util.CompoundDistribution'>
                  <distribution id='birthDeathMigration.t:complete N Gene fasta' spec='beast.evolution.speciation.BirthDeathMigrationModel'>

java.lang.RuntimeException: Error: frequencies must add up to 1 but currently add to 1.0000000000000004.
	at beast.evolution.speciation.PiecewiseBirthDeathMigrationDistribution.initAndValidate(Unknown Source)
	at beast.evolution.speciation.BirthDeathMigrationModel.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)"

Where Had I gone wrong, not able to understand. since it does not support XML file, so not able to attach it
Will really appreciate your help

Regards

**Comment by jscire** [comment]
Hello alka26,

Please try upgrading to BEAST 2.5 and bdmm 0.3.1 (or to the latest release). 
This should solve the issue.

Best,
Jeremie Scire

**Comment by jugne** [comment]
Closing due to no response. Please reopen if the issue persists.
